# This is a basic workflow to help you get started with Actions

name: "Build image"

on: [push]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup caching
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: "docker-${{ github.workflow }}"
          restore-keys: |
            docker-${{ github.workflow }}
            docker-

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          image-name: "deb-server"
          image-tag: "latest"
          dockerfile: "Dockerfile"
